#!/usr/bin/env bash

PATH=`npm bin`:$PATH

case "$1" in
  "spec")
    coffee -c ./spec/spec_helper.coffee
    jasmine-node --color --coffee "${@:2}" .
    ;;
  "compile")
    coffee --join lib/cream.js --compile "${@:2}" ./src
    ;;
  *)
    echo "No such build command: $1"
    ;;
esac;

